//created on: Apr 8, 2019
package org.nokia.opta.solver
    dialect "java"

import org.optaplanner.core.api.score.buildin.hardsoft.HardSoftScoreHolder;

import org.nokia.opta.FrequencyPlanner;
import org.nokia.opta.Band;
import org.nokia.opta.TRX;

global HardSoftScoreHolder scoreHolder;

// ############################################################################
// Hard constraints
// ############################################################################

rule "badNeighbours"
    when
        TRX( $freq : frequency, $neig : neighbours)
        TRX( badSeparation($freq) ) from $neig
    then
        scoreHolder.addHardConstraintMatch(kcontext, -10);
end


rule "badFarNeighbours"
    when
        TRX( $freq : frequency, $neig : neighbours)
        TRX( $neig_plus : neighbours ) from $neig
		TRX( badFarSeparation($freq) ) from $neig_plus
    then
        scoreHolder.addHardConstraintMatch(kcontext, -10);
end
